swagger: "2.0"
info:
  title: The goakit example downstream service
  description: Archiver is a service that manages the content of HTTP responses
  version: ""
host: localhost:80
paths:
  /archive:
    post:
      tags:
      - archiver
      summary: archive archiver
      description: Archive HTTP response
      operationId: archiver#archive
      parameters:
      - name: archiveRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/ArchiverarchiveRequestBody'
          required:
          - status
          - body
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ArchiverarchiveResponseBody'
      schemes:
      - grpc
      - http
  /archive/{id}:
    get:
      tags:
      - archiver
      summary: read archiver
      description: Read HTTP response from archive
      operationId: archiver#read
      parameters:
      - name: id
        in: path
        description: ID of archive
        required: true
        type: integer
        minimum: 0
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ArchiverreadResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/Archiverread_bad_requestResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/Archiverread_not_foundResponseBody'
      schemes:
      - grpc
      - http
  /health:
    get:
      tags:
      - health
      summary: show health
      description: Health check endpoint
      operationId: health#show
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - grpc
      - http
definitions:
  ArchiverarchiveRequestBody:
    title: ArchiverarchiveRequestBody
    type: object
    properties:
      body:
        type: string
        description: HTTP response body content
        example: Numquam qui qui eligendi doloribus.
      status:
        type: integer
        description: HTTP status
        example: 200
        minimum: 0
    example:
      body: Placeat aspernatur ullam qui numquam quis numquam.
      status: 200
    required:
    - status
    - body
  ArchiverarchiveResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.archive; view=default'
    type: object
    properties:
      body:
        type: string
        description: HTTP response body content
        example: Harum autem mollitia optio.
      href:
        type: string
        description: The archive resouce href
        example: /archive1/
        pattern: ^/archive/[0-9]+$
      status:
        type: integer
        description: HTTP status
        example: 200
        minimum: 0
    description: archiveResponseBody result type (default view)
    example:
      body: Alias ipsa eum laborum ut quod.
      href: /archive1/
      status: 200
    required:
    - href
    - status
    - body
  Archiverread_bad_requestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: read_bad_requestResponseBody result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  Archiverread_not_foundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: read_not_foundResponseBody result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ArchiverreadResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.archive; view=default'
    type: object
    properties:
      body:
        type: string
        description: HTTP response body content
        example: Quia cum qui numquam soluta iusto.
      href:
        type: string
        description: The archive resouce href
        example: /archive1/
        pattern: ^/archive/[0-9]+$
      status:
        type: integer
        description: HTTP status
        example: 200
        minimum: 0
    description: readResponseBody result type (default view)
    example:
      body: Ad beatae incidunt consequuntur aperiam aliquid.
      href: /archive1/
      status: 200
    required:
    - href
    - status
    - body
