language: go
go:
- 1.11.x
env:
  matrix:
install:
- export PATH=${PATH}:${HOME}/gopath/bin
script:
- export PATH=${PATH}:${HOME}/bin
- cd ../../.. && mkdir goa.design && cp -r github.com/goadesign/plugins goa.design/plugins && cd goa.design/plugins
- make
