{{if .Title}}// Code generated by goa {{.ToolVersion}}.
//
// {{.Title}}
//
// Command:
{{comment commandLine}}

{{end}}package {{.Pkg}}

{{if .Imports}}import {{if gt (len .Imports) 1}}(
{{range .Imports}}	{{if .Name}}{{.Name}} {{end}}{{.Path | printf "%q"}}
{{end}}){{else}}{{with index .Imports 0}}{{if .Name}}{{.Name}} {{end}}{{.Path | printf "%q"}}{{end}}{{end}}
{{end}}