openapi: 3.2.0
info:
    title: Calculator Service
    version: 0.0.1
servers:
    - url: http://localhost:80
      name: calc
      description: Default server for calc
paths:
    /add/{left}/{right}:
        get:
            tags:
                - calc
            summary: add calc
            operationId: calc#add
            parameters:
                - name: left
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: integer
                    description: Left operand
                    example: 4214196853188143223
                    format: int64
                  example: 4214196853188143223
                - name: right
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: integer
                    description: Right operand
                    example: 1249315168498320761
                    format: int64
                  example: 1249315168498320761
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 7371373013862544951
                                format: int64
                            example: 7371373013862544951
    /swagger.json:
        get:
            tags:
                - calc
            summary: Download ../../gen/http/openapi.json
            operationId: calc#/swagger.json
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: calc
      description: The calc service performs additions on numbers
