openapi: 3.2.0
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      name: Arnz
      description: Default server for Arnz
paths:
    /:
        delete:
            tags:
                - Arnz
            summary: delete Arnz
            operationId: Arnz#delete
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Qui illo.
        get:
            tags:
                - Arnz
            summary: read Arnz
            operationId: Arnz#read
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Accusantium est non molestiae.
        post:
            tags:
                - Arnz
            summary: create Arnz
            operationId: Arnz#create
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Aut sit sit repellendus nesciunt minima.
        put:
            tags:
                - Arnz
            summary: update Arnz
            operationId: Arnz#update
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Consectetur recusandae.
    /health:
        get:
            tags:
                - Arnz
            summary: health Arnz
            operationId: Arnz#health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Culpa sed.
components:
    schemas:
        ResponseBody:
            type: object
            properties:
                action:
                    type: string
                    example: Aut sit sit repellendus nesciunt minima.
            example:
                action: Aut sit sit repellendus nesciunt minima.
            required:
                - action
tags:
    - name: Arnz
