#! /usr/bin/make
#
# Makefile for goa v3 zerologger plugin

# include common Makefile content for plugins
include ../plugins.mk

gen:
# nothing to do

build-examples:
# nothing to do

clean:
# nothing to do