package dsl

import (
	"goa.design/goa/v3/eval"
	goaexpr "goa.design/goa/v3/expr"
	"goa.design/plugins/v3/docs"
	plugexpr "goa.design/plugins/v3/docs/expr"
)

// init registers the docs plugin when importing the DSL.
func init() { docs.Register() }

// UseJSONTags configures the docs plugin to use JSON struct tags declared via
// Meta("struct:tag:json", ...) as field names in generated docs.
//
// This setting affects type definitions, payloads, results, and error schemas
// and their examples.
//
// Usage:
//
//	var _ = API("my api", func() {
//		// Use field names from struct JSON tags throughout docs.json
//		docs.UseJSONTags()
//	})
func UseJSONTags() { plugexpr.Root.UseJSONTags = true }

// InlineRefs configures the docs plugin to inline referenced schemas in JSON
// Schema output where possible. Cycles are preserved by keeping $ref where
// needed (e.g., recursive references).
//
// Usage:
//
//	var _ = API("my api", func() {
//		// Prefer inlined schemas rather than $ref when there are no cycles
//		docs.InlineRefs()
//	})
func InlineRefs() { plugexpr.Root.InlineRefs = true }

// IncludeTypes registers user types to force-emit in docs.json definitions.
// Accepts user types defined via Type or ResultType.
//
// Service and method schemas are always generated by the docs plugin when not
// disabled on the service/method. IncludeTypes does not change service/method
// emission. This is only useful for types that are generated via the "force"
// Goa Meta DSL; it ensures those user types (and their transitive dependencies)
// are included under the top-level "definitions" object.
//
// Usage:
//
//	var _ = API("my api", func() {
//		// Ensure these shared types appear in docs.json definitions so downstream
//		// tooling can resolve schemas by name.
//		docs.IncludeTypes(MySharedType, AnotherType)
//	})
func IncludeTypes(ts ...goaexpr.UserType) { plugexpr.Root.IncludeTypes(ts...) }

// DisableDocs disables docs.json generation for the current service or method.
// It does not affect OpenAPI generation. Invoke inside a Service or Method DSL.
//
//	Service("front", func() {
//	    DisableDocs()
//	    // ... methods ...
//	})
func DisableDocs() {
	switch cur := eval.Current().(type) {
	case *goaexpr.ServiceExpr:
		if cur.Meta == nil {
			cur.Meta = make(goaexpr.MetaExpr)
		}
		cur.Meta["docs:generate"] = []string{"false"}
	case *goaexpr.MethodExpr:
		if cur.Meta == nil {
			cur.Meta = make(goaexpr.MetaExpr)
		}
		cur.Meta["docs:generate"] = []string{"false"}
	}
}
