swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /http/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream test-http-grpc
            operationId: test-http-grpc#http_no_stream
            parameters:
                - name: http_no_stream_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamResponseBody'
                        required:
                            - out
            schemes:
                - http
    /http/no-stream-error:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream_error test-http-grpc
            operationId: test-http-grpc#http_no_stream_error
            parameters:
                - name: http_no_stream_error_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamErrorRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamErrorResponseBody'
                        required:
                            - out
                "400":
                    description: 'division_by_zero: Division by zero error'
                    schema:
                        $ref: '#/definitions/DivisionByZeroError'
                        required:
                            - message
            schemes:
                - http
    /http/sse:
        post:
            tags:
                - test-http-grpc
            summary: http_server_stream_sse test-http-grpc
            operationId: test-http-grpc#http_server_stream_sse
            produces:
                - text/event-stream
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPServerStreamSseResponseBody'
                        required:
                            - event
            schemes:
                - http
    /http/ws/bidi:
        get:
            tags:
                - test-http-grpc
            summary: http_bidi_stream_ws test-http-grpc
            operationId: test-http-grpc#http_bidi_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPBidiStreamWsResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /http/ws/client:
        get:
            tags:
                - test-http-grpc
            summary: http_client_stream_ws test-http-grpc
            operationId: test-http-grpc#http_client_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPClientStreamWsResponseBody'
                        required:
                            - out
            schemes:
                - ws
    /http/ws/server:
        get:
            tags:
                - test-http-grpc
            summary: http_server_stream_ws test-http-grpc
            operationId: test-http-grpc#http_server_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPServerStreamWsResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /mixed/bidi-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_bidi_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_bidi_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /mixed/client-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_client_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_client_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedClientStreamWsGrpcResponseBody'
                        required:
                            - out
            schemes:
                - ws
    /mixed/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_no_stream test-http-grpc
            operationId: test-http-grpc#mixed_no_stream
            parameters:
                - name: mixed_no_stream_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcMixedNoStreamRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedNoStreamResponseBody'
                        required:
                            - out
            schemes:
                - http
    /mixed/server-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_server_stream test-http-grpc
            operationId: test-http-grpc#mixed_server_stream
            produces:
                - text/event-stream
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedServerStreamResponseBody'
                        required:
                            - event
            schemes:
                - http
definitions:
    DivisionByZeroError:
        title: DivisionByZeroError
        type: object
        properties:
            message:
                type: string
                description: division by zero error message
                example: Dolore eum provident autem iste.
        example:
            message: Dolore eum provident autem iste.
        required:
            - message
    TestHTTPGrpcHTTPBidiStreamWsResponseBody:
        title: TestHTTPGrpcHTTPBidiStreamWsResponseBody
        type: object
        properties:
            message:
                type: string
                example: Quaerat suscipit minus.
        example:
            message: Quaerat suscipit minus.
        required:
            - message
    TestHTTPGrpcHTTPClientStreamWsResponseBody:
        title: TestHTTPGrpcHTTPClientStreamWsResponseBody
        type: object
        properties:
            out:
                type: string
                example: Nihil eos.
        example:
            out: Nihil eos.
        required:
            - out
    TestHTTPGrpcHTTPNoStreamErrorRequestBody:
        title: TestHTTPGrpcHTTPNoStreamErrorRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Ipsum asperiores omnis culpa.
        example:
            msg: Ipsum asperiores omnis culpa.
        required:
            - msg
    TestHTTPGrpcHTTPNoStreamErrorResponseBody:
        title: TestHTTPGrpcHTTPNoStreamErrorResponseBody
        type: object
        properties:
            out:
                type: string
                example: Voluptatum et et incidunt.
        example:
            out: Voluptatum et et incidunt.
        required:
            - out
    TestHTTPGrpcHTTPNoStreamRequestBody:
        title: TestHTTPGrpcHTTPNoStreamRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Expedita eum recusandae non.
        example:
            msg: Expedita eum recusandae non.
        required:
            - msg
    TestHTTPGrpcHTTPNoStreamResponseBody:
        title: TestHTTPGrpcHTTPNoStreamResponseBody
        type: object
        properties:
            out:
                type: string
                example: Et quam quia et.
        example:
            out: Et quam quia et.
        required:
            - out
    TestHTTPGrpcHTTPServerStreamSseResponseBody:
        title: TestHTTPGrpcHTTPServerStreamSseResponseBody
        type: object
        properties:
            event:
                type: string
                example: Dolores cupiditate voluptatem voluptatibus accusantium sit.
        example:
            event: Dolores cupiditate voluptatem voluptatibus accusantium sit.
        required:
            - event
    TestHTTPGrpcHTTPServerStreamWsResponseBody:
        title: TestHTTPGrpcHTTPServerStreamWsResponseBody
        type: object
        properties:
            message:
                type: string
                example: Et sunt.
        example:
            message: Et sunt.
        required:
            - message
    TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody:
        title: TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody
        type: object
        properties:
            message:
                type: string
                example: Eum qui nam rerum eveniet ducimus dolores.
        example:
            message: Eum qui nam rerum eveniet ducimus dolores.
        required:
            - message
    TestHTTPGrpcMixedClientStreamWsGrpcResponseBody:
        title: TestHTTPGrpcMixedClientStreamWsGrpcResponseBody
        type: object
        properties:
            out:
                type: string
                example: Porro soluta.
        example:
            out: Porro soluta.
        required:
            - out
    TestHTTPGrpcMixedNoStreamRequestBody:
        title: TestHTTPGrpcMixedNoStreamRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Repellendus fuga quisquam sunt eligendi ad praesentium.
        example:
            msg: Repellendus fuga quisquam sunt eligendi ad praesentium.
        required:
            - msg
    TestHTTPGrpcMixedNoStreamResponseBody:
        title: TestHTTPGrpcMixedNoStreamResponseBody
        type: object
        properties:
            out:
                type: string
                example: Alias consequuntur culpa suscipit quasi.
        example:
            out: Alias consequuntur culpa suscipit quasi.
        required:
            - out
    TestHTTPGrpcMixedServerStreamResponseBody:
        title: TestHTTPGrpcMixedServerStreamResponseBody
        type: object
        properties:
            event:
                type: string
                example: Autem aliquid quis praesentium odit.
        example:
            event: Autem aliquid quis praesentium odit.
        required:
            - event
