openapi: 3.2.0
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      name: test-http-grpc
      description: Default server for test-http-grpc
paths:
    /http/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream test-http-grpc
            operationId: test-http-grpc#http_no_stream
            requestBody:
                description: Request body for http_no_stream.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HTTPNoStreamRequestBody'
                        example:
                            msg: Omnis animi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPNoStreamResponseBody'
                            example:
                                out: Inventore libero laudantium veniam sunt aut.
    /http/no-stream-error:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream_error test-http-grpc
            operationId: test-http-grpc#http_no_stream_error
            requestBody:
                description: Request body for http_no_stream_error.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HTTPNoStreamRequestBody'
                        example:
                            msg: Reiciendis consequatur.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPNoStreamResponseBody'
                            example:
                                out: Aut unde laboriosam modi incidunt occaecati sed.
                "400":
                    description: 'division_by_zero: Division by zero error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivisionByZeroError'
                            example:
                                message: Ducimus quae sed et consequatur autem.
    /http/sse:
        post:
            tags:
                - test-http-grpc
            summary: http_server_stream_sse test-http-grpc
            operationId: test-http-grpc#http_server_stream_sse
            responses:
                "200":
                    description: OK response.
                    content:
                        text/event-stream:
                            itemSchema:
                                type: object
                                properties:
                                    data:
                                        type: string
                                        contentMediaType: application/json
                                        contentSchema:
                                            $ref: '#/components/schemas/HTTPServerStreamSseResponseBody'
                                required:
                                    - data
    /http/ws/bidi:
        get:
            tags:
                - test-http-grpc
            summary: http_bidi_stream_ws test-http-grpc
            operationId: test-http-grpc#http_bidi_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivisionByZeroError'
                            example:
                                message: Quos ipsam rerum.
    /http/ws/client:
        get:
            tags:
                - test-http-grpc
            summary: http_client_stream_ws test-http-grpc
            operationId: test-http-grpc#http_client_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPNoStreamResponseBody'
                            example:
                                out: Id vel.
    /http/ws/server:
        get:
            tags:
                - test-http-grpc
            summary: http_server_stream_ws test-http-grpc
            operationId: test-http-grpc#http_server_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivisionByZeroError'
                            example:
                                message: Modi quaerat.
    /mixed/bidi-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_bidi_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_bidi_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivisionByZeroError'
                            example:
                                message: Maiores magni voluptatem consequatur voluptatem sed.
    /mixed/client-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_client_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_client_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPNoStreamResponseBody'
                            example:
                                out: Ipsum et doloremque.
    /mixed/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_no_stream test-http-grpc
            operationId: test-http-grpc#mixed_no_stream
            requestBody:
                description: Request body for mixed_no_stream.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/HTTPNoStreamRequestBody'
                        example:
                            msg: Sequi aut totam eum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPNoStreamResponseBody'
                            example:
                                out: Sunt voluptatum consequatur vitae facere est.
    /mixed/server-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_server_stream test-http-grpc
            operationId: test-http-grpc#mixed_server_stream
            responses:
                "200":
                    description: OK response.
                    content:
                        text/event-stream:
                            itemSchema:
                                type: object
                                properties:
                                    data:
                                        type: string
                                        contentMediaType: application/json
                                        contentSchema:
                                            $ref: '#/components/schemas/HTTPServerStreamSseResponseBody'
                                required:
                                    - data
components:
    schemas:
        DivisionByZeroError:
            type: object
            properties:
                message:
                    type: string
                    description: division by zero error message
                    example: Ducimus quae sed et consequatur autem.
            description: Division by zero error
            example:
                message: Ducimus quae sed et consequatur autem.
            required:
                - message
        HTTPNoStreamRequestBody:
            type: object
            properties:
                msg:
                    type: string
                    example: Omnis animi.
            description: Request body for http_no_stream.
            example:
                msg: Omnis animi.
            required:
                - msg
        HTTPNoStreamResponseBody:
            type: object
            properties:
                out:
                    type: string
                    example: Inventore libero laudantium veniam sunt aut.
            example:
                out: Inventore libero laudantium veniam sunt aut.
            required:
                - out
        HTTPServerStreamSseResponseBody:
            type: object
            properties:
                event:
                    type: string
                    example: Vitae ipsam eum aliquam corporis sed architecto.
            example:
                event: Vitae ipsam eum aliquam corporis sed architecto.
            required:
                - event
tags:
    - name: test-http-grpc
      description: Testing plugin matrix across HTTP and gRPC transports
