swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /http/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream test-http-grpc
            operationId: test-http-grpc#http_no_stream
            parameters:
                - name: http_no_stream_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamResponseBody'
                        required:
                            - out
            schemes:
                - http
    /http/no-stream-error:
        post:
            tags:
                - test-http-grpc
            summary: http_no_stream_error test-http-grpc
            operationId: test-http-grpc#http_no_stream_error
            parameters:
                - name: http_no_stream_error_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamErrorRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPNoStreamErrorResponseBody'
                        required:
                            - out
                "400":
                    description: Division by zero error
                    schema:
                        $ref: '#/definitions/DivisionByZeroError'
                        required:
                            - message
            schemes:
                - http
    /http/sse:
        post:
            tags:
                - test-http-grpc
            summary: http_server_stream_sse test-http-grpc
            operationId: test-http-grpc#http_server_stream_sse
            produces:
                - text/event-stream
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPServerStreamSseResponseBody'
                        required:
                            - event
            schemes:
                - http
    /http/ws/bidi:
        get:
            tags:
                - test-http-grpc
            summary: http_bidi_stream_ws test-http-grpc
            operationId: test-http-grpc#http_bidi_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPBidiStreamWsResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /http/ws/client:
        get:
            tags:
                - test-http-grpc
            summary: http_client_stream_ws test-http-grpc
            operationId: test-http-grpc#http_client_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPClientStreamWsResponseBody'
                        required:
                            - out
            schemes:
                - ws
    /http/ws/server:
        get:
            tags:
                - test-http-grpc
            summary: http_server_stream_ws test-http-grpc
            operationId: test-http-grpc#http_server_stream_ws
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcHTTPServerStreamWsResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /mixed/bidi-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_bidi_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_bidi_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody'
                        required:
                            - message
            schemes:
                - ws
    /mixed/client-stream/ws:
        get:
            tags:
                - test-http-grpc
            summary: mixed_client_stream_ws_grpc test-http-grpc
            operationId: test-http-grpc#mixed_client_stream_ws_grpc
            responses:
                "101":
                    description: Switching Protocols response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedClientStreamWsGrpcResponseBody'
                        required:
                            - out
            schemes:
                - ws
    /mixed/no-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_no_stream test-http-grpc
            operationId: test-http-grpc#mixed_no_stream
            parameters:
                - name: mixed_no_stream_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TestHTTPGrpcMixedNoStreamRequestBody'
                    required:
                        - msg
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedNoStreamResponseBody'
                        required:
                            - out
            schemes:
                - http
    /mixed/server-stream:
        post:
            tags:
                - test-http-grpc
            summary: mixed_server_stream test-http-grpc
            operationId: test-http-grpc#mixed_server_stream
            produces:
                - text/event-stream
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TestHTTPGrpcMixedServerStreamResponseBody'
                        required:
                            - event
            schemes:
                - http
definitions:
    DivisionByZeroError:
        title: DivisionByZeroError
        type: object
        properties:
            message:
                type: string
                description: division by zero error message
                example: Ducimus quae sed et consequatur autem.
        description: Division by zero error
        example:
            message: Ducimus quae sed et consequatur autem.
        required:
            - message
    TestHTTPGrpcHTTPBidiStreamWsResponseBody:
        title: TestHTTPGrpcHTTPBidiStreamWsResponseBody
        type: object
        properties:
            message:
                type: string
                example: Quos ipsam rerum.
        example:
            message: Quos ipsam rerum.
        required:
            - message
    TestHTTPGrpcHTTPClientStreamWsResponseBody:
        title: TestHTTPGrpcHTTPClientStreamWsResponseBody
        type: object
        properties:
            out:
                type: string
                example: Id vel.
        example:
            out: Id vel.
        required:
            - out
    TestHTTPGrpcHTTPNoStreamErrorRequestBody:
        title: TestHTTPGrpcHTTPNoStreamErrorRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Reiciendis consequatur.
        example:
            msg: Reiciendis consequatur.
        required:
            - msg
    TestHTTPGrpcHTTPNoStreamErrorResponseBody:
        title: TestHTTPGrpcHTTPNoStreamErrorResponseBody
        type: object
        properties:
            out:
                type: string
                example: Aut unde laboriosam modi incidunt occaecati sed.
        example:
            out: Aut unde laboriosam modi incidunt occaecati sed.
        required:
            - out
    TestHTTPGrpcHTTPNoStreamRequestBody:
        title: TestHTTPGrpcHTTPNoStreamRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Omnis animi.
        example:
            msg: Omnis animi.
        required:
            - msg
    TestHTTPGrpcHTTPNoStreamResponseBody:
        title: TestHTTPGrpcHTTPNoStreamResponseBody
        type: object
        properties:
            out:
                type: string
                example: Inventore libero laudantium veniam sunt aut.
        example:
            out: Inventore libero laudantium veniam sunt aut.
        required:
            - out
    TestHTTPGrpcHTTPServerStreamSseResponseBody:
        title: TestHTTPGrpcHTTPServerStreamSseResponseBody
        type: object
        properties:
            event:
                type: string
                example: Vitae ipsam eum aliquam corporis sed architecto.
        example:
            event: Vitae ipsam eum aliquam corporis sed architecto.
        required:
            - event
    TestHTTPGrpcHTTPServerStreamWsResponseBody:
        title: TestHTTPGrpcHTTPServerStreamWsResponseBody
        type: object
        properties:
            message:
                type: string
                example: Modi quaerat.
        example:
            message: Modi quaerat.
        required:
            - message
    TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody:
        title: TestHTTPGrpcMixedBidiStreamWsGrpcResponseBody
        type: object
        properties:
            message:
                type: string
                example: Maiores magni voluptatem consequatur voluptatem sed.
        example:
            message: Maiores magni voluptatem consequatur voluptatem sed.
        required:
            - message
    TestHTTPGrpcMixedClientStreamWsGrpcResponseBody:
        title: TestHTTPGrpcMixedClientStreamWsGrpcResponseBody
        type: object
        properties:
            out:
                type: string
                example: Ipsum et doloremque.
        example:
            out: Ipsum et doloremque.
        required:
            - out
    TestHTTPGrpcMixedNoStreamRequestBody:
        title: TestHTTPGrpcMixedNoStreamRequestBody
        type: object
        properties:
            msg:
                type: string
                example: Sequi aut totam eum.
        example:
            msg: Sequi aut totam eum.
        required:
            - msg
    TestHTTPGrpcMixedNoStreamResponseBody:
        title: TestHTTPGrpcMixedNoStreamResponseBody
        type: object
        properties:
            out:
                type: string
                example: Sunt voluptatum consequatur vitae facere est.
        example:
            out: Sunt voluptatum consequatur vitae facere est.
        required:
            - out
    TestHTTPGrpcMixedServerStreamResponseBody:
        title: TestHTTPGrpcMixedServerStreamResponseBody
        type: object
        properties:
            event:
                type: string
                example: Ab est voluptas in et.
        example:
            event: Ab est voluptas in et.
        required:
            - event
