name: build
on: [push, pull_request]
jobs:

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22'
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4    

    - name: Extract branch name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Add $GOPATH/bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      id: setup_path

    - name: Build
      run: make ci
